Allow .env.local file for local development
helxplatform/eduhelx-grader-api pull request #28
Opened 2024-02-05 22:53 UTC by Hoid

As of this PR, devs can create a file called `.env.local` as a copy of `.env.sample` in the root of the project and set values for all of the environment variables that need to be set. Previously, we had to change the config.py file manually to have the default values during development and make sure not to upload them to source control which was a major hassle. This will become even more useful once Harit merges his testing PR, since it fixes this issue in the Testing pane of vscode. 

The way I have it, it shouldn't have any effect if the `.env.local` file is not there, but we should keep an eye on it once we deploy this to a hosted environment with environment variables like Kubernetes for the first time.

2024-02-05 23:05 UTC, frostyfan109 approved these changes

2024-02-05 23:06 UTC, frostyfan109 commented
@Hoid I think start.py already loads `.env`, so maybe do it there instead of in settings?

2024-02-06 04:24 UTC, ptlharit2 approved these changes

2024-03-07 19:45 UTC, frostyfan109 requested changes
Need to update README about how to use .env.local

2024-03-07 19:45 UTC, frostyfan109 commented on app/core/config.py
> -    POSTGRES_PORT: str = "5432"
Why was the default value removed here?

2024-08-09 16:40 UTC, closed without merging